### ISSUE TITLE
java samples are missing

### ISSUE THREAD

**Issue by nagkumar** [klothoplatform/sample-apps#108]
Can you pl. add java sprint examples as shown in your mail screen that says java supported too

![image](https://github.com/klothoplatform/sample-apps/assets/332234/77619eda-2818-444d-a864-da847dfdad6e)
https://klo.dev/

**Comment by ghost** [comment]
Hey @nagkumar apologies for the late reply! We haven't released the Java version just yet - this reflects the design we're heading towards!
